import { SS58Address } from '@torus-network/sdk/types';

export const E2E_TEST_USER_ADDRESS = '5CdUwzzcNoK3veokWYaZoAn1rYTCKjmVwFYCWni54fDQm8pJ' as SS58Address;
export const OLD_BOT_DETECTOR_AGENT_ADDRESS = '5FCKLnjXSR8Dwe6AS93tnGvnAmDsnNqivvfWcjjsFEBC4i4V' as SS58Address;
export const PREDICTION_DETECTOR_AGENT_ADDRESS = '5GEUxJ9TpLQHfbaUAMx6RB4iJ2duLY7oswaXqn9rcEpAvWKQ' as SS58Address;
export const PREDICTION_FINDER_AGENT_ADDRESS = '5ExhSX83sbkorNwpBTZL3pBxX6PDMB2kKZjvwkMxpNKCP2Yh' as SS58Address;
export const PREDICTION_VERIFIER_AGENT_ADDRESS = '5GKvHYoaKKr6jWYM7FiUY6i7JZsaUfXrCdfEhFL89BxnCTCB' as SS58Address;
export const OPENROUTER_ROUTER_AGENT_ADDRESS = '5EexhTdfBsLVE99HGS5mQEMj86FoejXHmhZstKajEX8CvotT' as SS58Address;
export const VERDICT_REASONING_AGENT_ADDRESS = '5HTkSenPbzHNHSajcczw9jdXmAAopZ95crVPKpHw1wi4qdY5' as SS58Address;
export const PERPLEXITY_BRIDGE_AGENT_ADDRESS = '5Dd8xNBAr4EkFTjgxovuvSimzFdZTH9gyn5Jn5DzC3HuXJFC' as SS58Address;
export const PREDICTION_CONTEXT_FINDER_AGENT_ADDRESS = '5FhFGE4z1fnNas9izBjMrDK72qtFvFogcCe62SqZgKrBG2fT' as SS58Address;
export const PROXY_REQUEST_AGENT_ADDRESS = '5E1wLXgq2ab3FJ1xMRVYk282kse9DUXjyM8ReuYkwdR2hkwN' as SS58Address;
