#!/bin/sh
echo "Running pre-commit hook..."

echo "🔍 Step 1: Running lint-staged..."
npx lint-staged
echo "✅ lint-staged complete."

echo "🔎 Step 2: Running type-check..."
# We need to run this on all files, not just the staged ones
bun run type-check
echo "✅ type-check complete."

echo "📦 Step 3: Running build..."
# We need to build all files, not just the staged ones
bun run build
echo "✅ build complete."


echo "✅ All checks passed."
